# Generated by Django 6.0.3 on 2026-03-25 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='listings')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_approved', models.BooleanField(default=False)),
                ('businessname', models.CharField(max_length=250)),
                ('listing_title', models.CharField(max_length=250)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=250)),
                ('zip', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('map_link', models.URLField(verbose_name='listing location')),
                ('is_wifi', models.BooleanField(default=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('is_storage', models.BooleanField(default=False)),
                ('is_mirror', models.BooleanField(default=False)),
                ('is_sink', models.BooleanField(default=False)),
                ('is_styling_chair', models.BooleanField(default=False)),
                ('is_product_shelves', models.BooleanField(default=False)),
                ('is_access_24_hours', models.BooleanField(default=False)),
                ('amenities_description', models.TextField()),
                ('rental_type', models.CharField(max_length=250)),
                ('lease_terms', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('availability_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], default='draft', max_length=250)),
                ('maximum_cccupancy', models.IntegerField()),
                ('restrictions', models.TextField()),
                ('additional_notes', models.TextField()),
                ('crearor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(related_name='photos_and_media', to='jayla_models.photo_media')),
            ],
        ),
    ]
