# Generated by Django 6.0.3 on 2026-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayla_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_admin_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
