# Generated by Django 6.0.3 on 2026-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('listing_limit', models.IntegerField()),
                ('media_limit', models.IntegerField()),
                ('is_unlimited_listing', models.BooleanField(default=False)),
                ('is_able_analytics', models.BooleanField(default=False)),
                ('features', models.ManyToManyField(related_name='subscription_plans', to='subscribtions.feature')),
            ],
        ),
    ]
